name: "Stale issue handler"

on:
  workflow_dispatch:
  schedule:
    - cron: "40 23 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'popcn-ui'
    steps:
      - uses: actions/stale@v9
        id: issue-stale
        name: "Mark stale issues, close stale issues"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ascending: true
          days-before-issue-close: 14
          days-before-issue-stale: 180
          days-before-pr-stale: -1
          days-before-pr-close: -1
          remove-issue-stale-when-updated: true
          stale-issue-label: "stale"
          exempt-issue-labels: "roadmap,pinned"
          stale-issue-message: "This issue has been automatically marked as stale due to 180 days of inactivity. It will be closed in 14 days unless there's further input. If you believe this issue is still relevant, please leave a comment. (This is an automated message)"
          close-issue-message: "This issue has been automatically closed due to inactivity. If you're still experiencing a similar problem, please open a new issue. Thank you for your understanding. (This is an automated message)"
          operations-per-run: 300
      - uses: actions/stale@v9
        id: pr-stale
        name: "Mark stale PRs, close stale PRs"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ascending: true
          days-before-issue-close: -1
          days-before-issue-stale: -1
          days-before-pr-close: 14
          days-before-pr-stale: 180
          remove-pr-stale-when-updated: true
          stale-pr-label: "stale"
          exempt-pr-labels: "roadmap,pinned"
          stale-pr-message: "This PR has been automatically marked as stale due to 180 days of inactivity. It will be closed in 14 days unless there's further input. If you believe this PR is still relevant, please leave a comment. (This is an automated message)"
          close-pr-message: "This PR has been automatically closed due to inactivity. Thank you for your understanding. (This is an automated message)"
          operations-per-run: 300
